version: "3.4"
services:
    php:
        container_name: "php"
        build:
            context: .
            dockerfile: ./php.dockerfile
            args:
                PHP_DOCKER_VERSION: ${PHP_DOCKER_VERSION}
        volumes:
            - "${GITHUB_WORKSPACE}:/ChineseUtil:rw"
        working_dir: /ChineseUtil
        ulimits:
            core: -1
        privileged: true
        command: tail -f /etc/group
